(function (global) {
  'use strict';
  const tabs = [['overview','Sistem özeti'],['history','Geçmişler'],['timeline','Olay zaman çizelgesi'],['flows','Belirti akışları']];
  const stages = ['Alarm history','System alarm history','FSSB alarm history','Operation history','Kontrol','Bakım','Sonuç'];
  const view = { from: '', to: '', page: 1 };
  let activeTab = 'overview', selectedMachineId = null;
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const active = () => global.MTBRecordRepository?.active(global.State?.diagnostic_history || []) || [];
  const persist = () => global.DataPersistence?.saveDiagnosticHistory?.();
  const machineFor = id => (global.State?.machines || []).find(machine => String(machine.id) === String(id));
  const machineName = id => machineFor(id)?.numarasi || machineFor(id)?.name || 'Tezgâh belirtilmedi';
  const records = () => active().filter(record => !selectedMachineId || String(record.machineId ?? record.tezgah_id) === String(selectedMachineId));
  const create = input => global.MTBRecordRepository.create(global.State?.diagnostic_history || [], { ...input, machineId: selectedMachineId || null, deviceId: localStorage.getItem('mtb-drive-device-id') || 'local-device' }, global.State?.currentUser);
  const header = (title, detail) => `<div class="dh-section-head"><div><h2>${esc(title)}</h2><p>${esc(detail)}</p></div></div>`;
  const empty = (title, detail) => `<div class="dh-empty" role="status"><strong>${esc(title)}</strong><span>${esc(detail)}</span></div>`;
  const getSorted = () => (global.getSortedMachines ? global.getSortedMachines() : [...(global.State?.machines || [])].filter(m => !m.deletedAt).sort((a, b) => String(a.numarasi || a.name || '').localeCompare(String(b.numarasi || b.name || ''), 'tr', { numeric: true, sensitivity: 'base' })));
  function selector() { return `<label class="form-label" for="dh-machine">Tezgâh bağlamı</label><select id="dh-machine" class="form-control"><option value="">Tüm tezgâhlar</option>${getSorted().map(machine => `<option value="${esc(machine.id)}" ${String(machine.id) === String(selectedMachineId) ? 'selected' : ''}>${esc(machine.numarasi || machine.name)}</option>`).join('')}</select>`; }
  function overview() {
    const machine = machineFor(selectedMachineId) || getSorted()[0], profile = machine?.fanucProfile || {};
    return `${header('System Configuration özeti','Kayıtlar seçilen tezgâha bağlanır; uygulama CNC’ye veri yazmaz.')}<div class="dh-grid">${[['Tezgâh',machine?.numarasi||machine?.name],['Kontrol serisi',profile.series],['CNC yazılımı',profile.software],['FSSB current / I/O',profile.topology]].map(([key,value]) => `<article class="dh-card"><span>${esc(key)}</span><strong>${esc(value || 'Canlı veri yok')}</strong></article>`).join('')}</div><div class="dh-notice">Fan Monitor, Leakage Detection Monitor ve Waveform Diagnosis değerleri yalnız bağlı salt-okunur adaptörden alınabilir. Kapsam: FANUC B-64605EN/01; seri ve OEM dokümanıyla doğrulayın.</div>`;
  }
  function history() {
    const sorted = records().sort((a,b) => String(b.createdAt || b.time).localeCompare(String(a.createdAt || a.time)));
    const growth = global.MTBHistoryGrowth;
    const result = growth?.query(sorted, { ...view, pageSize: 100 }) || { rows: sorted.slice(0,100), total: sorted.length, page: 1, pages: Math.max(1,Math.ceil(sorted.length/100)) };
    const years = growth?.years(sorted) || [];
    return `${header('Birleşik teşhis geçmişi','Alarm, sistem alarmı, FSSB, kontrol, bakım ve sonuçları aynı olay altında kaydedin.')}<form class="dh-form" data-dh-form><label>Aşama<select name="type">${stages.map(stage => `<option>${stage}</option>`).join('')}</select></label><label>Olay kimliği<input name="incidentId" maxlength="60" placeholder="Örn. ALM-2026-004"></label><label>Kod / olay<input name="code" maxlength="60" required></label><label>Açıklama<input name="note" maxlength="240" required></label><button class="btn btn-primary" type="submit">Kaydet</button></form><div class="card" style="padding:12px;margin:12px 0"><div class="flex gap-2 items-end"><label>Başlangıç<input class="form-control" type="date" data-dh-from value="${esc(view.from)}"></label><label>Bitiş<input class="form-control" type="date" data-dh-to value="${esc(view.to)}"></label><button class="btn btn-secondary" data-dh-filter>Filtrele</button>${years.length ? `<label>Yıllık arşiv<select class="form-control" data-dh-year>${years.map(year => `<option>${year}</option>`).join('')}</select></label><button class="btn btn-secondary" data-dh-export>CSV dışa aktar</button>` : ''}<span class="tag tag-gray">${result.total} kayıt</span></div></div><div class="dh-table-wrap">${result.rows.length ? `<table class="dh-table"><thead><tr><th>Zaman</th><th>Tezgâh</th><th>Aşama</th><th>Olay</th><th>Açıklama</th><th></th></tr></thead><tbody>${result.rows.map(record => `<tr><td>${esc(new Date(record.createdAt || record.time).toLocaleString('tr-TR'))}</td><td>${esc(machineName(record.machineId ?? record.tezgah_id))}</td><td>${esc(record.type)}</td><td>${esc(record.incidentId || record.code)}</td><td>${esc(record.note)}</td><td><button class="btn btn-ghost btn-sm" data-dh-delete="${esc(record.id)}">Sil</button></td></tr>`).join('')}</tbody></table>` : empty('Kayıt bulunamadı','Seçilen tezgâh ve tarih aralığı için ilk gözlemi ekleyin.')}</div><div class="flex justify-between items-center"><button class="btn btn-secondary" data-dh-page="${result.page-1}" ${result.page<=1?'disabled':''}>Önceki</button><span>Sayfa ${result.page} / ${result.pages}</span><button class="btn btn-secondary" data-dh-page="${result.page+1}" ${result.page>=result.pages?'disabled':''}>Sonraki</button></div>`;
  }
  function timeline() { const groups = new Map(); records().forEach(record => { const key=record.incidentId||record.code||record.id; if(!groups.has(key))groups.set(key,[]); groups.get(key).push(record); }); return `${header('Alarmdan sonuca zaman çizelgesi','Alarm → sistem alarmı → FSSB → kontrol → bakım → sonuç ilerleyişi.')}<div class="dh-flow-list">${[...groups].map(([key,list]) => `<article class="dh-flow"><h3>${esc(key)} · ${esc(machineName(list[0]?.machineId))}</h3><ol>${stages.map(stage => { const items=list.filter(item=>item.type===stage); return `<li class="${items.length?'complete':'pending'}"><strong>${esc(stage)}</strong>${items.length?items.map(item=>`<span>${esc(item.note)} <small>${esc(new Date(item.createdAt).toLocaleString('tr-TR'))}</small></span>`).join(''):'<span>Henüz kayıt yok</span>'}</li>`; }).join('')}</ol></article>`).join('') || empty('Zaman çizelgesi yok','Geçmişler sekmesinde aynı olay kimliğiyle aşamalar ekleyin.')}</div>`; }
  function flows() { const items=[['CNC açılmıyor','Besleme göstergesi → acil stop zinciri → ilk alarm → yetkili ölçüm'],['Manuel hareket yok','Çalışma modu → machine lock → PMC izinleri → alarm geçmişi'],['Referansa dönemiyor','APZ alarmı → limit durumu → pil geçmişi → OEM prosedürü'],['Servo ready oluşmuyor','İlk alarm → PSM/SVM LED → FSSB düğümleri → üretici prosedürü'],['Spindle dönmüyor','Alarm → izin sinyalleri → SPM LED → bakım sonucu'],['I/O Link sorunu','Grup/kanal → modül LED → PMC status → yetkili kontrol']]; return `${header('Güvenli teşhis akışları','Salt-okunur gözlem ve kayıt içindir; kilitleri bypass etmeyin.')}<div class="dh-grid">${items.map(([title,detail]) => `<article class="dh-card"><strong>${esc(title)}</strong><p>${esc(detail)}</p></article>`).join('')}</div>`; }
  function content() { return ({overview,history,timeline,flows}[activeTab] || overview)(); }
  function bind(page) {
    page.querySelector('#dh-machine')?.addEventListener('change', event => { selectedMachineId=event.target.value||null; view.page=1; render(); });
    page.querySelectorAll('[data-dh-tab]').forEach(button => button.addEventListener('click', () => { activeTab=button.dataset.dhTab; render(); }));
    page.querySelector('[data-dh-filter]')?.addEventListener('click', () => { view.from=page.querySelector('[data-dh-from]').value; view.to=page.querySelector('[data-dh-to]').value; view.page=1; render(); });
    page.querySelectorAll('[data-dh-page]').forEach(button => button.addEventListener('click', () => { view.page=Number(button.dataset.dhPage); render(); }));
    page.querySelector('[data-dh-export]')?.addEventListener('click', () => { const year=page.querySelector('[data-dh-year]').value; const count=global.MTBHistoryGrowth?.exportYear(records(),year)||0; global.showToast?.(`${count} teşhis kaydı dışa aktarıldı.`,'success'); });
    page.querySelector('[data-dh-form]')?.addEventListener('submit', async event => { event.preventDefault(); if(!selectedMachineId){global.showToast?.('Önce bir tezgâh seçin.','warning');return;} const fd=new FormData(event.currentTarget); global.State.diagnostic_history ||= []; global.State.diagnostic_history.push(create({type:fd.get('type'),incidentId:fd.get('incidentId')||fd.get('code'),code:fd.get('code'),note:fd.get('note')})); await persist(); render(); global.showToast?.('Teşhis kaydı senkronizasyona hazır.','success'); });
    page.querySelectorAll('[data-dh-delete]').forEach(button => button.addEventListener('click', async () => { const out=global.MTBRecordRepository.archiveById(global.State.diagnostic_history,button.dataset.dhDelete,global.State.currentUser); global.State.diagnostic_history=out.records; await persist(); render(); }));
  }
  function render(extraData=null) { if(extraData?.machineId)selectedMachineId=extraData.machineId; const page=global.createPage?global.createPage('diagnostic_history'):document.getElementById('page-diagnostic_history'); if(!page)return; page.innerHTML=`<div class="page-header"><h1>Teşhis ve Geçmiş Merkezi</h1><p>Tezgâh bağlamlı olay takibi ve güvenli kontrol akışları</p><div style="max-width:320px">${selector()}</div></div><div class="page-body"><div class="dh-tabs" role="tablist">${tabs.map(([id,label])=>`<button role="tab" aria-selected="${id===activeTab}" class="${id===activeTab?'active':''}" data-dh-tab="${id}">${label}</button>`).join('')}</div><section class="dh-content">${content()}</section></div>`; bind(page); return page; }
  global.MTBDiagnosticHistory=Object.freeze({render});
})(window);
